"""Added new order and order item tables

Revision ID: 2e100ca128b5
Revises: da9b03cf2431
Create Date: 2024-05-23 12:03:00.181074

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e100ca128b5"
down_revision: Union[str, None] = "da9b03cf2431"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("order_amount", sa.Integer(), nullable=False),
        sa.Column(
            "order_status",
            sa.Enum("pending", "confirmed", "cancelled", "shipping", "delivered", name="status"),
            nullable=False,
        ),
        sa.Column("shipping_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orderitem",
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orderitem")
    op.drop_table("order")
    # ### end Alembic commands ###
