"""Update relationship for order item table

Revision ID: 3b162805afc3
Revises: 95f8b435914c
Create Date: 2024-05-23 18:27:37.317685

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b162805afc3"
down_revision: Union[str, None] = "95f8b435914c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order",
        "order_amount",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.add_column("orderitem", sa.Column("product_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "orderitem", "product", ["product_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orderitem", type_="foreignkey")  # type: ignore
    op.drop_column("orderitem", "product_id")
    op.alter_column(
        "order",
        "order_amount",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
