"""Update one-one relationship for cart and order 

Revision ID: 95f8b435914c
Revises: 2e100ca128b5
Create Date: 2024-05-23 12:42:44.292810

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95f8b435914c"
down_revision: Union[str, None] = "2e100ca128b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("cart_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "order", "cart", ["cart_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order", type_="foreignkey")  # type: ignore
    op.drop_column("order", "cart_id")
    # ### end Alembic commands ###
