"""Remove index for primary keys

Revision ID: da9b03cf2431
Revises: fb9396dfad5a
Create Date: 2024-05-23 10:22:55.234097

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da9b03cf2431"
down_revision: Union[str, None] = "fb9396dfad5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cart_id", table_name="cart")
    op.drop_index("ix_cartitem_id", table_name="cartitem")
    op.drop_index("ix_category_id", table_name="category")
    op.drop_index("ix_product_id", table_name="product")
    op.drop_index("ix_user_id", table_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_id", "user", ["id"], unique=False)
    op.create_index("ix_product_id", "product", ["id"], unique=False)
    op.create_index("ix_category_id", "category", ["id"], unique=False)
    op.create_index("ix_cartitem_id", "cartitem", ["id"], unique=False)
    op.create_index("ix_cart_id", "cart", ["id"], unique=False)
    # ### end Alembic commands ###
