"""Update date type for cart and cart item tables

Revision ID: fb9396dfad5a
Revises: 771031663db4
Create Date: 2024-05-23 09:39:14.033486

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fb9396dfad5a"
down_revision: Union[str, None] = "771031663db4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cart",
        "created_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore
    )
    op.alter_column(
        "cartitem",
        "created_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cartitem",
        "created_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore
    )
    op.alter_column(
        "cart",
        "created_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore
    )
    # ### end Alembic commands ###
